spring.datasource.url=jdbc:h2:mem:brainstormdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enable=true

spring.jpa.hibernate.ddl-auto=create
spring.jap.show-sql=true

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

springdoc.swagger-ui.path=/docs