spring.application.name=brainstorm-api
spring.profiles.active=dev

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

springdoc.swagger-ui.path=/docs

jwt.secret=brainstorm-dev-secret-key-must-be-at-least-256-bits
jwt.expiration=604800000